[package]
name = "basics"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = "*"
actix-session = {version="*", features = ["cookie-session"] }
actix-web = "*"
dotenv = "*"

async-stream = "0.3"
env_logger = "*"
log = "*"
